#! /bin/sh
PATH=/sbin:/bin:/user/sbin:/usr/bin
LD_LIBRARY_PATH=/lib
export PATH LD_LIBRARY_PATH

echo "1"
mount -a
echo "2"
mkdir -p /dev/pts
echo "3"
mount -t devpts devpts dev/pts
echo "4"
mdev -s
echo "5"
mkdir -p /var/lock
echo "6"

echo "Welcome to qemu linux!"
